### ISSUE TITLE
TODO: Documentation Drive. document replicate.block and replicate.upto

### ISSUE THREAD

**Issue by hardfire** [ssbc/ssb-replicate#3]
Rate the current state of the documentation out of 10 
 - 6 (Purely based on feeling)

is it clear what this is used for?
 - No, Need to mention more details on replication (maybe link to the right part of ssb protocol)/

is there api documentation?
 - Yes

read code, do you see any undocumented methods?
 - Yes. The following methods are undocumented
 - `replicate.block`
 - `replicate.upto` -  Not a method but undocumented 

for a method is there any undocumented options?
  - No. The methods that are documented have mentioned the options.

**Comment by dominictarr** [comment]
TODO: document undocumented methods. reassigning this as a Village Tracker task.
