### ISSUE TITLE
Add support for ssb-conn

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-replicate#8]
@staltz I've been trying out ssb-conn in Oasis but I'm consistently getting a deprecation notice from this module. Any suggestions on which ssb-conn-specific code should be used here instead?

https://github.com/ssbc/ssb-replicate/blob/81ab9f6d6ad4009af88735d80ff0ace93a6dd54e/legacy.js#L231-L239

**Comment by staltz** [comment]
@christianbundy I think we could just delete that code, as the `// XXX` comment indicates. But if you want to match exactly that functionality, I think it would be:

```js
ssbServer.conn.query().peersConnected().forEach(function (e) {
  if (e[1].type === 'lan')
    request(e[0])
})
```
